### ISSUE TITLE
Epic: Create Stamen Map Tile Vending Machine

### ISSUE THREAD

**Issue by mizmay** [stamen/maps.stamen.com#203]
Let's create a "vending machine" for tiles, e.g. a web interface that allows anyone to pay and download the Stamen Map tiles they want from AWS.

A script or CLI can happen in parallel, but keep it simple. With this epic we're more looking for a proof of concept with a cute front end. File spikes for the deeper questions and investigations you are tempted to pursue.

Acceptance criteria:

1. [ ] Has a front-end
2. [ ] Works for Toner
3. [ ] User can pay and download (a range of) tiles

Bonus if we can implement:
- [ ] Work for tiles in a bounding box
- [ ] User can specify a range of zooms
- [ ] Works for tiles in the viewport
- [ ] Works for Terrain
- [ ] Works for Watercolor
- [ ] Works for the various variants of Toner, Terrain, Watercolor

DRI: @almccon

**Comment by almccon** [comment]
Notes filling in here: https://docs.google.com/document/d/1zcMmMvChx4DS9xtye023HhU797DG5lnS3M9PjfH2t8g/edit#

**Comment by almccon** [comment]
See also the more elaborate "map in a cloud box" idea https://github.com/stamen/carto-tools/issues/30 which this tool definitely _is not_.
